// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.5.0
// source: novel_spider/model.proto

package novel_spider_interface

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// NovelStatus 小说状态
type NovelStatus int32

const (
	// NOVEL_STATUS_UNDEFINED 未定义
	NovelStatus_NOVEL_STATUS_UNDEFINED NovelStatus = 0
	// NOVEL_STATUS_SERIALIZE 连载中
	NovelStatus_NOVEL_STATUS_SERIALIZE NovelStatus = 1
	// NOVEL_STATUS_FINISH 完结
	NovelStatus_NOVEL_STATUS_FINISH NovelStatus = 2
)

// Enum value maps for NovelStatus.
var (
	NovelStatus_name = map[int32]string{
		0: "NOVEL_STATUS_UNDEFINED",
		1: "NOVEL_STATUS_SERIALIZE",
		2: "NOVEL_STATUS_FINISH",
	}
	NovelStatus_value = map[string]int32{
		"NOVEL_STATUS_UNDEFINED": 0,
		"NOVEL_STATUS_SERIALIZE": 1,
		"NOVEL_STATUS_FINISH":    2,
	}
)

func (x NovelStatus) Enum() *NovelStatus {
	p := new(NovelStatus)
	*p = x
	return p
}

func (x NovelStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NovelStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_novel_spider_model_proto_enumTypes[0].Descriptor()
}

func (NovelStatus) Type() protoreflect.EnumType {
	return &file_novel_spider_model_proto_enumTypes[0]
}

func (x NovelStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NovelStatus.Descriptor instead.
func (NovelStatus) EnumDescriptor() ([]byte, []int) {
	return file_novel_spider_model_proto_rawDescGZIP(), []int{0}
}

// NovelInfo 小说信息
type NovelInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID .
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// name 名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// author 作者
	Author string `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	// introduction 介绍
	Introduction string `protobuf:"bytes,4,opt,name=introduction,proto3" json:"introduction,omitempty"`
	// cover 封面
	Cover string `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover,omitempty"`
	// status 状态
	Status NovelStatus `protobuf:"varint,6,opt,name=status,proto3,enum=novel_spider.NovelStatus" json:"status,omitempty"`
	// trilateralNo 三方编号
	TrilateralNo string `protobuf:"bytes,7,opt,name=trilateralNo,proto3" json:"trilateralNo,omitempty"`
	// souceNo 来源编号
	SouceNo int64 `protobuf:"varint,8,opt,name=souceNo,proto3" json:"souceNo,omitempty"`
	// souceName 来源名称
	SouceName string `protobuf:"bytes,9,opt,name=souceName,proto3" json:"souceName,omitempty"`
	// URL 网址
	URL string `protobuf:"bytes,10,opt,name=URL,proto3" json:"URL,omitempty"`
	// updatedAt 更新时间
	UpdatedAt int64 `protobuf:"varint,11,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *NovelInfo) Reset() {
	*x = NovelInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_novel_spider_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NovelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NovelInfo) ProtoMessage() {}

func (x *NovelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_novel_spider_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NovelInfo.ProtoReflect.Descriptor instead.
func (*NovelInfo) Descriptor() ([]byte, []int) {
	return file_novel_spider_model_proto_rawDescGZIP(), []int{0}
}

func (x *NovelInfo) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *NovelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NovelInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *NovelInfo) GetIntroduction() string {
	if x != nil {
		return x.Introduction
	}
	return ""
}

func (x *NovelInfo) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *NovelInfo) GetStatus() NovelStatus {
	if x != nil {
		return x.Status
	}
	return NovelStatus_NOVEL_STATUS_UNDEFINED
}

func (x *NovelInfo) GetTrilateralNo() string {
	if x != nil {
		return x.TrilateralNo
	}
	return ""
}

func (x *NovelInfo) GetSouceNo() int64 {
	if x != nil {
		return x.SouceNo
	}
	return 0
}

func (x *NovelInfo) GetSouceName() string {
	if x != nil {
		return x.SouceName
	}
	return ""
}

func (x *NovelInfo) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *NovelInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// NovelChapter 小说章节
type NovelChapter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// name 名字
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// content 内容
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// URL 网址
	URL string `protobuf:"bytes,4,opt,name=URL,proto3" json:"URL,omitempty"`
}

func (x *NovelChapter) Reset() {
	*x = NovelChapter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_novel_spider_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NovelChapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NovelChapter) ProtoMessage() {}

func (x *NovelChapter) ProtoReflect() protoreflect.Message {
	mi := &file_novel_spider_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NovelChapter.ProtoReflect.Descriptor instead.
func (*NovelChapter) Descriptor() ([]byte, []int) {
	return file_novel_spider_model_proto_rawDescGZIP(), []int{1}
}

func (x *NovelChapter) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *NovelChapter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NovelChapter) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NovelChapter) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

var File_novel_spider_model_proto protoreflect.FileDescriptor

var file_novel_spider_model_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x5f, 0x73, 0x70, 0x69, 0x64, 0x65, 0x72, 0x2f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6e, 0x6f, 0x76, 0x65,
	0x6c, 0x5f, 0x73, 0x70, 0x69, 0x64, 0x65, 0x72, 0x22, 0xc0, 0x02, 0x0a, 0x09, 0x4e, 0x6f, 0x76,
	0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x6e,
	0x6f, 0x76, 0x65, 0x6c, 0x5f, 0x73, 0x70, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x4e, 0x6f, 0x76, 0x65,
	0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x22, 0x0a, 0x0c, 0x74, 0x72, 0x69, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x4e, 0x6f, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x72, 0x69, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x61,
	0x6c, 0x4e, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6f, 0x75, 0x63, 0x65, 0x4e, 0x6f, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x6f, 0x75, 0x63, 0x65, 0x4e, 0x6f, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x6f, 0x75, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x6f, 0x75, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55,
	0x52, 0x4c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x52, 0x4c, 0x12, 0x1c, 0x0a,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x5e, 0x0a, 0x0c, 0x4e,
	0x6f, 0x76, 0x65, 0x6c, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x52, 0x4c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x52, 0x4c, 0x2a, 0x5e, 0x0a, 0x0b, 0x4e,
	0x6f, 0x76, 0x65, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x16, 0x4e, 0x4f,
	0x56, 0x45, 0x4c, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x44, 0x45, 0x46,
	0x49, 0x4e, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x4e, 0x4f, 0x56, 0x45, 0x4c, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x45, 0x52, 0x49, 0x41, 0x4c, 0x49, 0x5a, 0x45,
	0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x4e, 0x4f, 0x56, 0x45, 0x4c, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x10, 0x02, 0x42, 0x41, 0x5a, 0x3f, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x76, 0x7a, 0x68, 0x61, 0x6f,
	0x68, 0x75, 0x61, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2f, 0x76, 0x31,
	0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x5f, 0x73, 0x70,
	0x69, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_novel_spider_model_proto_rawDescOnce sync.Once
	file_novel_spider_model_proto_rawDescData = file_novel_spider_model_proto_rawDesc
)

func file_novel_spider_model_proto_rawDescGZIP() []byte {
	file_novel_spider_model_proto_rawDescOnce.Do(func() {
		file_novel_spider_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_novel_spider_model_proto_rawDescData)
	})
	return file_novel_spider_model_proto_rawDescData
}

var file_novel_spider_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_novel_spider_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_novel_spider_model_proto_goTypes = []interface{}{
	(NovelStatus)(0),     // 0: novel_spider.NovelStatus
	(*NovelInfo)(nil),    // 1: novel_spider.NovelInfo
	(*NovelChapter)(nil), // 2: novel_spider.NovelChapter
}
var file_novel_spider_model_proto_depIdxs = []int32{
	0, // 0: novel_spider.NovelInfo.status:type_name -> novel_spider.NovelStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_novel_spider_model_proto_init() }
func file_novel_spider_model_proto_init() {
	if File_novel_spider_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_novel_spider_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NovelInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_novel_spider_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NovelChapter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_novel_spider_model_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_novel_spider_model_proto_goTypes,
		DependencyIndexes: file_novel_spider_model_proto_depIdxs,
		EnumInfos:         file_novel_spider_model_proto_enumTypes,
		MessageInfos:      file_novel_spider_model_proto_msgTypes,
	}.Build()
	File_novel_spider_model_proto = out.File
	file_novel_spider_model_proto_rawDesc = nil
	file_novel_spider_model_proto_goTypes = nil
	file_novel_spider_model_proto_depIdxs = nil
}
