// Code generated by protoc-gen-go-enum. DO NOT EDIT.

package novel_spider_interface

// Enum display name maps for NovelStatus.
var NovelStatus_displayName = map[int32]string{
	0: "不限",
	1: "连载中",
	2: "完结",
}

// Enum display name maps for NovelSource.
var NovelSource_displayName = map[int32]string{
	0: "不限",
	1: "笔趣阁u",
}
