// Code generated by protoc-gen-go-rpcx. DO NOT EDIT.

package novel_spider_interface

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DefaultRPCXServer is the server API for DefaultRPCX service.
// All implementations should embed UnimplementedDefaultRPCXServer
// for forward compatibility
type DefaultRPCXServer interface {
	// SearchNovel 搜索小说
	SearchNovel(context.Context, *SearchNovelRequest, *SearchNovelReply) error
	// SearchMenu 搜索目录
	SearchMenu(context.Context, *SearchMenuRequest, *SearchMenuReply) error
	// SearchChapter 搜索章节
	SearchChapter(context.Context, *SearchChapterRequest, *SearchChapterReply) error
}

// UnimplementedDefaultRPCXServer should be embedded to have forward compatible implementations.
type UnimplementedDefaultRPCXServer struct {
}

func (UnimplementedDefaultRPCXServer) SearchNovel(context.Context, *SearchNovelRequest, *SearchNovelReply) error {
	return status.Errorf(codes.Unimplemented, "method SearchNovel not implemented")
}
func (UnimplementedDefaultRPCXServer) SearchMenu(context.Context, *SearchMenuRequest, *SearchMenuReply) error {
	return status.Errorf(codes.Unimplemented, "method SearchMenu not implemented")
}
func (UnimplementedDefaultRPCXServer) SearchChapter(context.Context, *SearchChapterRequest, *SearchChapterReply) error {
	return status.Errorf(codes.Unimplemented, "method SearchChapter not implemented")
}

func RegisterDefaultRPCXServer(s grpc.ServiceRegistrar, srv DefaultRPCXServer) {
	s.RegisterService(&DefaultRPCX_ServiceDesc, srv)
}

// DefaultRPCX_ServiceDesc is the grpc.ServiceDesc for DefaultRPCX service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DefaultRPCX_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "novel_spider.Default",
	HandlerType: (*DefaultRPCXServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchNovel",
		},
		{
			MethodName: "SearchMenu",
		},
		{
			MethodName: "SearchChapter",
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "novel_spider/service.proto",
}
