// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.6
// source: tripurx_shopping/service.proto

package tripurx_shopping_interface

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// GetSpuRequest 获取Spu返回请求
type GetSpuRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpuID int64 `protobuf:"varint,1,opt,name=spuID,proto3" json:"spuID,omitempty"`
}

func (x *GetSpuRequest) Reset() {
	*x = GetSpuRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tripurx_shopping_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpuRequest) ProtoMessage() {}

func (x *GetSpuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tripurx_shopping_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpuRequest.ProtoReflect.Descriptor instead.
func (*GetSpuRequest) Descriptor() ([]byte, []int) {
	return file_tripurx_shopping_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetSpuRequest) GetSpuID() int64 {
	if x != nil {
		return x.SpuID
	}
	return 0
}

// GetSpuReply 获取Spu返回
type GetSpuReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *SpuInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *GetSpuReply) Reset() {
	*x = GetSpuReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tripurx_shopping_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpuReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpuReply) ProtoMessage() {}

func (x *GetSpuReply) ProtoReflect() protoreflect.Message {
	mi := &file_tripurx_shopping_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpuReply.ProtoReflect.Descriptor instead.
func (*GetSpuReply) Descriptor() ([]byte, []int) {
	return file_tripurx_shopping_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetSpuReply) GetInfo() *SpuInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// LoginRequest 登录
type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   int64  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tripurx_shopping_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tripurx_shopping_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_tripurx_shopping_service_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *LoginRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type LoginReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tripurx_shopping_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_tripurx_shopping_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_tripurx_shopping_service_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_tripurx_shopping_service_proto protoreflect.FileDescriptor

var file_tripurx_shopping_service_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x74, 0x72, 0x69, 0x70, 0x75, 0x72, 0x78, 0x5f, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x10, 0x74, 0x72, 0x69, 0x70, 0x75, 0x72, 0x78, 0x5f, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x1a, 0x1c, 0x74, 0x72, 0x69, 0x70, 0x75, 0x72, 0x78, 0x5f, 0x73, 0x68, 0x6f, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x25, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x70, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x75, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x73, 0x70, 0x75, 0x49, 0x44, 0x22, 0x3c, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x70,
	0x75, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2d, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x74, 0x72, 0x69, 0x70, 0x75, 0x72, 0x78, 0x5f, 0x73,
	0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x70, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x42, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x22, 0x0a, 0x0a, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0x9a, 0x01,
	0x0a, 0x07, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x48, 0x0a, 0x06, 0x47, 0x65, 0x74,
	0x53, 0x70, 0x75, 0x12, 0x1f, 0x2e, 0x74, 0x72, 0x69, 0x70, 0x75, 0x72, 0x78, 0x5f, 0x73, 0x68,
	0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x70, 0x75, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x74, 0x72, 0x69, 0x70, 0x75, 0x72, 0x78, 0x5f, 0x73,
	0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x70, 0x75, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x45, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1e, 0x2e, 0x74,
	0x72, 0x69, 0x70, 0x75, 0x72, 0x78, 0x5f, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2e,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x74,
	0x72, 0x69, 0x70, 0x75, 0x72, 0x78, 0x5f, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2e,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x76, 0x7a, 0x68, 0x61, 0x6f, 0x68,
	0x75, 0x61, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x67, 0x6f, 0x6c,
	0x61, 0x6e, 0x67, 0x2f, 0x74, 0x72, 0x69, 0x70, 0x75, 0x72, 0x78, 0x5f, 0x73, 0x68, 0x6f, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tripurx_shopping_service_proto_rawDescOnce sync.Once
	file_tripurx_shopping_service_proto_rawDescData = file_tripurx_shopping_service_proto_rawDesc
)

func file_tripurx_shopping_service_proto_rawDescGZIP() []byte {
	file_tripurx_shopping_service_proto_rawDescOnce.Do(func() {
		file_tripurx_shopping_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_tripurx_shopping_service_proto_rawDescData)
	})
	return file_tripurx_shopping_service_proto_rawDescData
}

var file_tripurx_shopping_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tripurx_shopping_service_proto_goTypes = []interface{}{
	(*GetSpuRequest)(nil), // 0: tripurx_shopping.GetSpuRequest
	(*GetSpuReply)(nil),   // 1: tripurx_shopping.GetSpuReply
	(*LoginRequest)(nil),  // 2: tripurx_shopping.LoginRequest
	(*LoginReply)(nil),    // 3: tripurx_shopping.LoginReply
	(*SpuInfo)(nil),       // 4: tripurx_shopping.SpuInfo
}
var file_tripurx_shopping_service_proto_depIdxs = []int32{
	4, // 0: tripurx_shopping.GetSpuReply.info:type_name -> tripurx_shopping.SpuInfo
	0, // 1: tripurx_shopping.Default.GetSpu:input_type -> tripurx_shopping.GetSpuRequest
	2, // 2: tripurx_shopping.Default.Login:input_type -> tripurx_shopping.LoginRequest
	1, // 3: tripurx_shopping.Default.GetSpu:output_type -> tripurx_shopping.GetSpuReply
	3, // 4: tripurx_shopping.Default.Login:output_type -> tripurx_shopping.LoginReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tripurx_shopping_service_proto_init() }
func file_tripurx_shopping_service_proto_init() {
	if File_tripurx_shopping_service_proto != nil {
		return
	}
	file_tripurx_shopping_model_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_tripurx_shopping_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpuRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tripurx_shopping_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpuReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tripurx_shopping_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tripurx_shopping_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tripurx_shopping_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tripurx_shopping_service_proto_goTypes,
		DependencyIndexes: file_tripurx_shopping_service_proto_depIdxs,
		MessageInfos:      file_tripurx_shopping_service_proto_msgTypes,
	}.Build()
	File_tripurx_shopping_service_proto = out.File
	file_tripurx_shopping_service_proto_rawDesc = nil
	file_tripurx_shopping_service_proto_goTypes = nil
	file_tripurx_shopping_service_proto_depIdxs = nil
}
