// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// UserInfo 表示用户信息, 只有自己能看到
type UserInfo struct {
	// ID 用户ID
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// userNum 是用户号, 展示在用户App界面上的
	UserNum string `protobuf:"bytes,2,opt,name=userNum,proto3" json:"userNum,omitempty"`
	// nickname 用户昵称
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// avatar 用户头像
	Avatar string `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	// phone 电话号码
	Phone string `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	// firstActiveTimeInApp 第一次在 app 里的活跃时间
	FirstActiveTimeInApp int32 `protobuf:"varint,6,opt,name=firstActiveTimeInApp,proto3" json:"firstActiveTimeInApp,omitempty"`
	// lastActiveTimeInApp 是最后一次在 app 里的活跃时间
	LastActiveTimeInApp int32 `protobuf:"varint,7,opt,name=lastActiveTimeInApp,proto3" json:"lastActiveTimeInApp,omitempty"`
	// createdAt 是用户创建时间
	CreatedAt int32 `protobuf:"varint,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// updatedAt 是用户更新时间(基本没有实际意义).
	UpdatedAt            int32    `protobuf:"varint,9,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UserInfo) GetUserNum() string {
	if m != nil {
		return m.UserNum
	}
	return ""
}

func (m *UserInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserInfo) GetFirstActiveTimeInApp() int32 {
	if m != nil {
		return m.FirstActiveTimeInApp
	}
	return 0
}

func (m *UserInfo) GetLastActiveTimeInApp() int32 {
	if m != nil {
		return m.LastActiveTimeInApp
	}
	return 0
}

func (m *UserInfo) GetCreatedAt() int32 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *UserInfo) GetUpdatedAt() int32 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "user.UserInfo")
}

func init() {
	proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8)
}

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xd0, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0x06, 0x70, 0xd9, 0x6d, 0xd2, 0xe4, 0x90, 0x18, 0x8e, 0x0a, 0x9d, 0x10, 0x43, 0xc4, 0x94,
	0x09, 0x21, 0x78, 0x82, 0x48, 0x5d, 0xbc, 0x30, 0x44, 0xf0, 0x00, 0x26, 0xb9, 0x0a, 0x8b, 0xfa,
	0x8f, 0x1c, 0xa7, 0xcf, 0xc3, 0xa3, 0xa2, 0xba, 0xa5, 0x0c, 0x74, 0xfc, 0xbe, 0xdf, 0x7d, 0xcb,
	0xc1, 0x95, 0xf5, 0x23, 0xef, 0x1e, 0x43, 0xf4, 0xc9, 0xe3, 0x72, 0x9e, 0x38, 0x3e, 0x7c, 0x4b,
	0xa8, 0xde, 0x27, 0x8e, 0xca, 0x6d, 0x3d, 0x5e, 0x83, 0x54, 0x1b, 0x12, 0x8d, 0x68, 0x17, 0xbd,
	0x54, 0x1b, 0x24, 0x58, 0x1d, 0x8e, 0x5e, 0x67, 0x4b, 0xb2, 0x11, 0x6d, 0xdd, 0xff, 0x46, 0xbc,
	0x83, 0xca, 0x99, 0xe1, 0xcb, 0x69, 0xcb, 0xb4, 0xc8, 0x74, 0xce, 0x78, 0x0b, 0xa5, 0xde, 0xeb,
	0xa4, 0x23, 0x2d, 0xb3, 0x9c, 0x12, 0xae, 0xa1, 0x08, 0x9f, 0xde, 0x31, 0x15, 0xb9, 0x3e, 0x06,
	0x7c, 0x86, 0xf5, 0xd6, 0xc4, 0x29, 0x75, 0x43, 0x32, 0x7b, 0x7e, 0x33, 0x96, 0x95, 0xeb, 0x42,
	0xa0, 0xb2, 0x11, 0x6d, 0xd1, 0x5f, 0x34, 0x7c, 0x82, 0x9b, 0x9d, 0xfe, 0x3f, 0x59, 0xe5, 0xc9,
	0x25, 0xc2, 0x7b, 0xa8, 0x87, 0xc8, 0x3a, 0xf1, 0xd8, 0x25, 0xaa, 0xf2, 0xdd, 0x5f, 0x71, 0xd0,
	0x39, 0x8c, 0x27, 0xad, 0x8f, 0x7a, 0x2e, 0x3e, 0xca, 0xfc, 0xaf, 0x97, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x1b, 0xef, 0x74, 0xdb, 0x3e, 0x01, 0x00, 0x00,
}
